spring:
  application:
    name: kidsworld

  datasource:
    url: jdbc:mysql://localhost:3306/kidsworld
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    pa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          naming:
          # show_sql: true
          format_sql: true
      #    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
